In [1]:
import os
import cv2
from glob import glob
import matplotlib.pyplot as plt
import pandas as pd
from functools import reduce
from xml.etree import ElementTree as et

In [2]:
##loading xml files
xmlfiles = glob('./data_images/*.xml')
#datacleaning
replace_text = lambda x: x.replace('\\','/')
xml_list = list(map(replace_text,xmlfiles))

In [3]:
xml_list

['./data_images/04ecd245-motorbike_0085.xml',
 './data_images/10573c8e-dog_0090.xml',
 './data_images/113003e8-car_0115.xml',
 './data_images/116e69df-airplane_0627.xml',
 './data_images/17784d59-motorbike_0099.xml',
 './data_images/1921e510-motorbike_0066.xml',
 './data_images/29be3592-person_0187.xml',
 './data_images/2bee9de4-dog_0084.xml',
 './data_images/2cac86c3-airplane_0586.xml',
 './data_images/32474c4e-person_0179.xml',
 './data_images/33045373-hr4.xml',
 './data_images/34d9f740-car_0117.xml',
 './data_images/35ea7f19-dog_0067.xml',
 './data_images/3644dc32-dog_0092.xml',
 './data_images/39500511-dog_0059.xml',
 './data_images/3d7af1a8-person_0180.xml',
 './data_images/3eb7022d-person_0176.xml',
 './data_images/4151a21b-airplane_0589.xml',
 './data_images/444ffcd6-motorbike_0065.xml',
 './data_images/45aee029-3.xml',
 './data_images/475383e1-airplane_0629.xml',
 './data_images/49706a9f-airplane_0628.xml',
 './data_images/49840592-airplane_0585.xml',
 './data_images/4a1ab8d7-person_0186.xml',
 './data_images/4a245f79-car_0089.xml',
 './data_images/4a6a4480-dog_0081.xml',
 './data_images/4ef7a026-airplane_0583.xml',
 './data_images/4f3b3a54-br4.xml',
 './data_images/531dad8b-person_0172.xml',
 './data_images/53aeaf4e-motorbike_0051.xml',
 './data_images/55bf0039-2.xml',
 './data_images/561537ab-br2.xml',
 './data_images/564cfa86-4.xml',
 './data_images/569d434a-car_0090.xml',
 './data_images/581de111-dog_0079.xml',
 './data_images/623f6da2-bus6.xml',
 './data_images/6473826b-airplane_0582.xml',
 './data_images/66ccbac9-2.xml',
 './data_images/6b843422-car_0119.xml',
 './data_images/7989cb0a-dog_0060.xml',
 './data_images/79f7b169-dog_0076.xml',
 './data_images/7a3719ef-5.xml',
 './data_images/7ade3531-bus3.xml',
 './data_images/7afda386-car_0109.xml',
 './data_images/7d538689-hr2.xml',
 './data_images/7e2729e3-car_0092.xml',
 './data_images/8124c265-car_0110.xml',
 './data_images/8d7e24f8-3.xml',
 './data_images/8ecadcd0-car_0091.xml',
 './data_images/9005d77c-dog_0045.xml',
 './data_images/90559556-car_0116.xml',
 './data_images/949db435-bus7.xml',
 './data_images/973e0c90-car_0125.xml',
 './data_images/993b7094-person_0177.xml',
 './data_images/998338b6-person_0175.xml',
 './data_images/9d473d76-motorbike_0068.xml',
 './data_images/9f984b70-car_0087.xml',
 './data_images/a21c2d4f-airplane_0584.xml',
 './data_images/a3f61bb4-hr1.xml',
 './data_images/a4003837-airplane_0587.xml',
 './data_images/a6591ab8-dog_0077.xml',
 './data_images/aceca466-person_0168.xml',
 './data_images/ae467a67-dog_0061.xml',
 './data_images/b0a12eaa-airplane_0588.xml',
 './data_images/b878f747-car_0093.xml',
 './data_images/b9555cf7-hr3.xml',
 './data_images/b9bfa62a-dog_0091.xml',
 './data_images/baa5ec6c-br1.xml',
 './data_images/c23ee283-bus8.xml',
 './data_images/c891c28f-person_0171.xml',
 './data_images/cb73af37-dog_0046.xml',
 './data_images/cb81b50c-bus1.xml',
 './data_images/d0d41c30-dog_0080.xml',
 './data_images/d1a9bc81-bus4.xml',
 './data_images/d5706038-dog_0049.xml',
 './data_images/dedd670d-car_0108.xml',
 './data_images/deefc9af-1.xml',
 './data_images/e0d36eea-car_0105.xml',
 './data_images/ef75bf34-br3.xml',
 './data_images/f3a143c5-motorbike_0052.xml',
 './data_images/f8d5864d-bus2.xml',
 './data_images/f980c231-motorbike_0050.xml',
 './data_images/fbe49472-dog_0088.xml',
 './data_images/fc28c640-car_0088.xml',
 './data_images/fc8a8959-dog_0083.xml',
 './data_images/fcbb17d3-car_0113.xml',
 './data_images/ffedcafd-br5.xml']

In [4]:
#step read xml files
#from each xml files we need to to extract
#filename, size(width , height) , object , (name , xmin , xmax , ymin , ymax)
def extract_text(filename):#helperfunction
    tree = et.parse(filename) #one image directory
    root = tree.getroot()
    # print(root)


    # #extract filenames
    # of the same images as above
    image_name = root.find('filename').text 
    #width =and height of the aimages
    width = root.find('size').find('width').text
    height = root.find('size').find('height').text

    objs = root.findall('object')
    parser = [] #empty list
    for obj in objs:
        obj = objs[0]
        name = obj.find('name').text
        bndbox = obj.find('bndbox')
        xmin = bndbox.find('xmin').text
        xmax = bndbox.find('xmax').text
        ymin = bndbox.find('ymin').text
        ymax = bndbox.find('ymax').text
        parser.append([image_name , width, height, name , xmin, xmax , ymin , ymax])
   
    return parser

In [5]:
parser_all = list(map(extract_text,xmlfiles))

In [6]:
parser_all

[[['04ecd245-motorbike_0085.jpg',
   '198',
   '102',
   'Bike',
   '3',
   '193',
   '11',
   '98']],
 [['10573c8e-dog_0090.jpg', '285', '377', 'Dog', '36', '272', '8', '337']],
 [['113003e8-car_0115.jpg', '100', '100', 'Car', '0', '99', '1', '98']],
 [['116e69df-airplane_0627.jpg',
   '300',
   '94',
   'Airplane',
   '3',
   '296',
   '1',
   '92']],
 [['17784d59-motorbike_0099.jpg',
   '198',
   '111',
   'Bike',
   '1',
   '192',
   '2',
   '106']],
 [['1921e510-motorbike_0066.jpg',
   '182',
   '117',
   'Bike',
   '0',
   '181',
   '0',
   '115']],
 [['29be3592-person_0187.jpg',
   '256',
   '256',
   'Person',
   '3',
   '217',
   '3',
   '239']],
 [['2bee9de4-dog_0084.jpg', '261', '445', 'Dog', '5', '246', '4', '401']],
 [['2cac86c3-airplane_0586.jpg',
   '283',
   '84',
   'Airplane',
   '3',
   '281',
   '4',
   '81']],
 [['32474c4e-person_0179.jpg',
   '256',
   '256',
   'Person',
   '30',
   '229',
   '0',
   '233']],
 [['33045373-hr4.jpg', '1024', '683', 'Person', '201', '558', '18', '661'],
  ['33045373-hr4.jpg', '1024', '683', 'Person', '201', '558', '18', '661']],
 [['34d9f740-car_0117.jpg', '100', '100', 'Car', '0', '99', '0', '95']],
 [['35ea7f19-dog_0067.jpg', '229', '227', 'Dog', '1', '228', '6', '207']],
 [['3644dc32-dog_0092.jpg', '171', '237', 'Dog', '3', '168', '2', '221']],
 [['39500511-dog_0059.jpg', '233', '434', 'Dog', '4', '228', '5', '414']],
 [['3d7af1a8-person_0180.jpg',
   '256',
   '256',
   'Person',
   '31',
   '251',
   '1',
   '230']],
 [['3eb7022d-person_0176.jpg',
   '256',
   '256',
   'Person',
   '40',
   '233',
   '1',
   '221']],
 [['4151a21b-airplane_0589.jpg',
   '292',
   '103',
   'Airplane',
   '2',
   '291',
   '2',
   '101']],
 [['444ffcd6-motorbike_0065.jpg',
   '199',
   '119',
   'Bike',
   '1',
   '198',
   '1',
   '118']],
 [['45aee029-3.jpeg', '1350', '900', 'Person', '761', '1093', '104', '899'],
  ['45aee029-3.jpeg', '1350', '900', 'Person', '761', '1093', '104', '899']],
 [['475383e1-airplane_0629.jpg',
   '295',
   '97',
   'Airplane',
   '3',
   '291',
   '0',
   '95']],
 [['49706a9f-airplane_0628.jpg',
   '299',
   '90',
   'Airplane',
   '8',
   '295',
   '0',
   '89']],
 [['49840592-airplane_0585.jpg',
   '304',
   '95',
   'Airplane',
   '9',
   '300',
   '1',
   '91']],
 [['4a1ab8d7-person_0186.jpg',
   '256',
   '256',
   'Person',
   '15',
   '231',
   '3',
   '236']],
 [['4a245f79-car_0089.jpg', '100', '100', 'Car', '6', '96', '3', '94']],
 [['4a6a4480-dog_0081.jpg', '385', '306', 'Dog', '16', '376', '8', '299']],
 [['4ef7a026-airplane_0583.jpg',
   '320',
   '124',
   'Airplane',
   '27',
   '314',
   '10',
   '117']],
 [['4f3b3a54-br4.jpg', '1619', '1080', 'Birds', '508', '1008', '107', '913']],
 [['531dad8b-person_0172.jpg',
   '256',
   '256',
   'Person',
   '3',
   '223',
   '6',
   '235']],
 [['53aeaf4e-motorbike_0051.jpg',
   '188',
   '110',
   'Bike',
   '1',
   '184',
   '2',
   '106']],
 [['55bf0039-2.png', '170', '126', 'Stingray', '2', '160', '4', '121']],
 [['561537ab-br2.jpg', '1602', '1659', 'Birds', '210', '1322', '87', '1616']],
 [['564cfa86-4.jpg', '533', '800', 'Stingray', '28', '517', '42', '737']],
 [['569d434a-car_0090.jpg', '100', '100', 'Car', '2', '97', '2', '97']],
 [['581de111-dog_0079.jpg', '260', '287', 'Dog', '10', '233', '9', '270']],
 [['623f6da2-bus6.jpg', '4001', '2554', 'Bus', '0', '3756', '347', '2350']],
 [['6473826b-airplane_0582.jpg',
   '299',
   '142',
   'Airplane',
   '3',
   '297',
   '4',
   '137']],
 [['66ccbac9-2.jpg', '334', '234', 'Stingray', '55', '258', '37', '169']],
 [['6b843422-car_0119.jpg', '100', '100', 'Car', '0', '99', '1', '97']],
 [['7989cb0a-dog_0060.jpg', '286', '220', 'Dog', '10', '273', '5', '213']],
 [['79f7b169-dog_0076.jpg', '171', '174', 'Dog', '7', '169', '3', '173']],
 [['7a3719ef-5.jpg', '3072', '2304', 'Stingray', '0', '3072', '208', '2123']],
 [['7ade3531-bus3.jpg', '2000', '1387', 'Bus', '170', '1901', '67', '1368']],
 [['7afda386-car_0109.jpg', '100', '100', 'Car', '0', '99', '1', '99']],
 [['7d538689-hr2.jpg', '3134', '2089', 'Person', '980', '1714', '234', '1471'],
  ['7d538689-hr2.jpg',
   '3134',
   '2089',
   'Person',
   '980',
   '1714',
   '234',
   '1471']],
 [['7e2729e3-car_0092.jpg', '100', '100', 'Car', '1', '97', '1', '98']],
 [['8124c265-car_0110.jpg', '100', '100', 'Car', '1', '98', '0', '96']],
 [['8d7e24f8-3.jpg', '474', '296', 'Stingray', '109', '381', '61', '274']],
 [['8ecadcd0-car_0091.jpg', '100', '100', 'Car', '1', '99', '0', '98']],
 [['9005d77c-dog_0045.jpg', '451', '338', 'Dog', '2', '440', '4', '327']],
 [['90559556-car_0116.jpg', '100', '100', 'Car', '0', '100', '0', '99']],
 [['949db435-bus7.jpg', '3872', '2592', 'Bus', '413', '3648', '136', '2436']],
 [['973e0c90-car_0125.jpg', '100', '100', 'Car', '1', '97', '1', '95']],
 [['993b7094-person_0177.jpg',
   '256',
   '256',
   'Person',
   '49',
   '255',
   '5',
   '235']],
 [['998338b6-person_0175.jpg',
   '256',
   '256',
   'Person',
   '28',
   '230',
   '5',
   '215']],
 [['9d473d76-motorbike_0068.jpg',
   '208',
   '151',
   'Bike',
   '4',
   '203',
   '3',
   '146']],
 [['9f984b70-car_0087.jpg', '100', '100', 'Car', '1', '97', '1', '97']],
 [['a21c2d4f-airplane_0584.jpg',
   '336',
   '88',
   'Airplane',
   '17',
   '327',
   '8',
   '86']],
 [['a3f61bb4-hr1.jpg', '369', '245', 'Person', '147', '250', '1', '147'],
  ['a3f61bb4-hr1.jpg', '369', '245', 'Person', '147', '250', '1', '147']],
 [['a4003837-airplane_0587.jpg',
   '299',
   '84',
   'Airplane',
   '0',
   '298',
   '1',
   '83']],
 [['a6591ab8-dog_0077.jpg', '391', '395', 'Dog', '23', '380', '18', '356']],
 [['aceca466-person_0168.jpg',
   '256',
   '256',
   'Person',
   '56',
   '234',
   '5',
   '222']],
 [['ae467a67-dog_0061.jpg', '188', '352', 'Dog', '14', '183', '11', '344']],
 [['b0a12eaa-airplane_0588.jpg',
   '291',
   '86',
   'Airplane',
   '2',
   '290',
   '2',
   '85']],
 [['b878f747-car_0093.jpg', '100', '100', 'Car', '0', '98', '0', '97']],
 [['b9555cf7-hr3.jpeg', '1350', '900', 'Person', '758', '1082', '94', '891'],
  ['b9555cf7-hr3.jpeg', '1350', '900', 'Person', '758', '1082', '94', '891']],
 [['b9bfa62a-dog_0091.jpg', '342', '335', 'Dog', '2', '329', '0', '263']],
 [['baa5ec6c-br1.jpg', '3000', '2048', 'Bike', '734', '2848', '267', '1747']],
 [['c23ee283-bus8.jpg', '1600', '1067', 'Bus', '286', '1215', '30', '924']],
 [['c891c28f-person_0171.jpg',
   '256',
   '256',
   'Person',
   '29',
   '234',
   '0',
   '234']],
 [['cb73af37-dog_0046.jpg', '238', '366', 'Dog', '23', '225', '8', '361']],
 [['cb81b50c-bus1.jpg', '474', '317', 'Bike', '8', '30', '106', '109'],
  ['cb81b50c-bus1.jpg', '474', '317', 'Bike', '8', '30', '106', '109']],
 [['d0d41c30-dog_0080.jpg', '289', '447', 'Dog', '17', '281', '12', '436']],
 [['d1a9bc81-bus4.jpg', '4596', '3262', 'Bus', '141', '4407', '443', '3090']],
 [['d5706038-dog_0049.jpg', '351', '310', 'Dog', '6', '345', '7', '291']],
 [['dedd670d-car_0108.jpg', '100', '100', 'Car', '1', '97', '1', '97']],
 [['deefc9af-1.jpg', '339', '234', 'Stingray', '50', '329', '88', '221']],
 [['e0d36eea-car_0105.jpg', '100', '100', 'Car', '1', '97', '3', '93']],
 [['ef75bf34-br3.jpg', '1024', '683', 'Birds', '103', '936', '50', '637']],
 [['f3a143c5-motorbike_0052.jpg',
   '206',
   '109',
   'Bike',
   '2',
   '205',
   '7',
   '108']],
 [['f8d5864d-bus2.jpg', '3354', '2304', 'Bike', '480', '2838', '300', '2182']],
 [['f980c231-motorbike_0050.jpg',
   '200',
   '100',
   'Bike',
   '1',
   '199',
   '7',
   '95']],
 [['fbe49472-dog_0088.jpg', '187', '277', 'Person', '33', '148', '7', '90'],
  ['fbe49472-dog_0088.jpg', '187', '277', 'Person', '33', '148', '7', '90']],
 [['fc28c640-car_0088.jpg', '100', '100', 'Car', '2', '94', '1', '97']],
 [['fc8a8959-dog_0083.jpg', '192', '243', 'Dog', '9', '182', '1', '196']],
 [['fcbb17d3-car_0113.jpg', '100', '100', 'Car', '0', '99', '0', '96']],
 [['ffedcafd-br5.jpg', '3708', '3012', 'Birds', '916', '3142', '365', '2684']]]

In [7]:
data = reduce(lambda x , y  : x+y, parser_all)

In [8]:
df = pd.DataFrame(data,columns = ['filename', 'width' , 'height' , 'name' , 'xmin' , 'xmax' , 'ymin' , 'ymax'])

In [9]:
df.head()
# df.shape

                      filename width height      name xmin xmax ymin ymax
0  04ecd245-motorbike_0085.jpg   198    102      Bike    3  193   11   98
1        10573c8e-dog_0090.jpg   285    377       Dog   36  272    8  337
2        113003e8-car_0115.jpg   100    100       Car    0   99    1   98
3   116e69df-airplane_0627.jpg   300     94  Airplane    3  296    1   92
4  17784d59-motorbike_0099.jpg   198    111      Bike    1  192    2  106

In [10]:
df['name'].value_counts()

name
Person      22
Dog         17
Car         17
Bike        12
Airplane    11
Stingray     6
Bus          5
Birds        4
Name: count, dtype: int64

In [11]:
df.head

<bound method NDFrame.head of                        filename width height      name xmin  xmax ymin  ymax
0   04ecd245-motorbike_0085.jpg   198    102      Bike    3   193   11    98
1         10573c8e-dog_0090.jpg   285    377       Dog   36   272    8   337
2         113003e8-car_0115.jpg   100    100       Car    0    99    1    98
3    116e69df-airplane_0627.jpg   300     94  Airplane    3   296    1    92
4   17784d59-motorbike_0099.jpg   198    111      Bike    1   192    2   106
..                          ...   ...    ...       ...  ...   ...  ...   ...
89        fbe49472-dog_0088.jpg   187    277    Person   33   148    7    90
90        fc28c640-car_0088.jpg   100    100       Car    2    94    1    97
91        fc8a8959-dog_0083.jpg   192    243       Dog    9   182    1   196
92        fcbb17d3-car_0113.jpg   100    100       Car    0    99    0    96
93             ffedcafd-br5.jpg  3708   3012     Birds  916  3142  365  2684

[94 rows x 8 columns]>

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  94 non-null     object
 1   width     94 non-null     object
 2   height    94 non-null     object
 3   name      94 non-null     object
 4   xmin      94 non-null     object
 5   xmax      94 non-null     object
 6   ymin      94 non-null     object
 7   ymax      94 non-null     object
dtypes: object(8)
memory usage: 6.0+ KB

In [13]:
df.info() #have to be in int , float values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  94 non-null     object
 1   width     94 non-null     object
 2   height    94 non-null     object
 3   name      94 non-null     object
 4   xmin      94 non-null     object
 5   xmax      94 non-null     object
 6   ymin      94 non-null     object
 7   ymax      94 non-null     object
dtypes: object(8)
memory usage: 6.0+ KB

In [14]:
#type conversion

cols = ['width' , 'height' , 'xmin' , 'xmax' , 'ymin', 'ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  94 non-null     object
 1   width     94 non-null     int32
 2   height    94 non-null     int32
 3   name      94 non-null     object
 4   xmin      94 non-null     int32
 5   xmax      94 non-null     int32
 6   ymin      94 non-null     int32
 7   ymax      94 non-null     int32
dtypes: int32(6), object(2)
memory usage: 3.8+ KB

In [16]:
# img = cv2.imread(r"C:\Users\SURUJ_KALITA\Desktop\pr-sd\myenv\1.png")
# plt.imshow(img)

In [17]:
##Performinf label

df['center_x'] = ((df['xmax']+df['xmin'])/2)/df['width']

df['center_x'] = ((df['ymax']+df['xmin'])/2)/df['height']

df['w'] = (df['xmax']-df['xmax'])/df['width']

df['h'] = (df['ymax']-df['ymax'])/df['height']

In [18]:
df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,w,h
0,04ecd245-motorbike_0085.jpg,198,102,Bike,3,193,11,98,0.495098,0.0,0.0
1,10573c8e-dog_0090.jpg,285,377,Dog,36,272,8,337,0.494695,0.0,0.0
2,113003e8-car_0115.jpg,100,100,Car,0,99,1,98,0.490000,0.0,0.0
3,116e69df-airplane_0627.jpg,300,94,Airplane,3,296,1,92,0.505319,0.0,0.0
4,17784d59-motorbike_0099.jpg,198,111,Bike,1,192,2,106,0.481982,0.0,0.0

# split data into train and text

In [19]:
images = df['filename'].unique()

In [20]:
len(images)

87

In [21]:
#training and testing
img_df = pd.DataFrame(images,columns=['filename'])  ##converting to dataframe
img_train = tuple(img_df.sample(frac=0.8)['filename']) ##siffle and picking images

In [22]:
img_test  = tuple(img_df.query(f'filename not in {img_train}')['filename'])

In [23]:
len(img_train), len(img_test)

(70, 17)

In [24]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [25]:
train_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,w,h
0,04ecd245-motorbike_0085.jpg,198,102,Bike,3,193,11,98,0.495098,0.0,0.0
1,10573c8e-dog_0090.jpg,285,377,Dog,36,272,8,337,0.494695,0.0,0.0
3,116e69df-airplane_0627.jpg,300,94,Airplane,3,296,1,92,0.505319,0.0,0.0
4,17784d59-motorbike_0099.jpg,198,111,Bike,1,192,2,106,0.481982,0.0,0.0
5,1921e510-motorbike_0066.jpg,182,117,Bike,0,181,0,115,0.491453,0.0,0.0

In [26]:
test_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,w,h
2,113003e8-car_0115.jpg,100,100,Car,0,99,1,98,0.490000,0.0,0.0
8,2cac86c3-airplane_0586.jpg,283,84,Airplane,3,281,4,81,0.500000,0.0,0.0
13,35ea7f19-dog_0067.jpg,229,227,Dog,1,228,6,207,0.458150,0.0,0.0
27,4a6a4480-dog_0081.jpg,385,306,Dog,16,376,8,299,0.514706,0.0,0.0
28,4ef7a026-airplane_0583.jpg,320,124,Airplane,27,314,10,117,0.580645,0.0,0.0

# Assign id number to object names

In [27]:
# Label Encoding
def label_encoding(x):
    labels = {'Person':0 , 'Dog':1 , 'Car':2 , 'Bike':3 , 'Airplane':4 , 'Stingray':5 , 'Bus':6 , 'Birds':7}
    return labels[x]

In [28]:
train_df['id'] = train_df['name'].apply(label_encoding)
test_df['id'] = test_df['name'].apply(label_encoding)

C:\Users\SURUJ_KALITA\AppData\Local\Temp\ipykernel_18256\3116627190.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['id'] = train_df['name'].apply(label_encoding)
C:\Users\SURUJ_KALITA\AppData\Local\Temp\ipykernel_18256\3116627190.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['id'] = test_df['name'].apply(label_encoding)

In [29]:
train_df.head()  ##Put the label encoding parameters to check eg 0 person 1 Dog

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,w,h,id
0,04ecd245-motorbike_0085.jpg,198,102,Bike,3,193,11,98,0.495098,0.0,0.0,3
1,10573c8e-dog_0090.jpg,285,377,Dog,36,272,8,337,0.494695,0.0,0.0,1
3,116e69df-airplane_0627.jpg,300,94,Airplane,3,296,1,92,0.505319,0.0,0.0,4
4,17784d59-motorbike_0099.jpg,198,111,Bike,1,192,2,106,0.481982,0.0,0.0,3
5,1921e510-motorbike_0066.jpg,182,117,Bike,0,181,0,115,0.491453,0.0,0.0,3

# Save Image and Labels in Text

In [30]:
###Saving Images and Labelling in sample.txt 
##save the sample.txt and train_imag under one folder
import os
from shutil import move

In [31]:
#https://www.youtube.com/watch?v=m9fH9OWn8YM&t=585s  Upto 22 convert imgaes .txt data 
# https://www.youtube.com/watch?v=mRhQmRm_egc&t=2s 1.03 -->

In [32]:
# ##Craeting btwo folder test fol,der and train folder 
# train_folder = 'data_images/train'
# test_folder = 'data_images/test'

# # train_folder = 'data_images/*'
# # test_folder = 'data_images/*'

# # os.mkdir(train_folder)
# # os.mkdir(test_folder)

In [33]:
cols = ['filename' , 'id' , 'center_x', 'name' , 'w' , 'h']

groupby_obj_train = train_df[cols].groupby('filename')
groupby_obj_test = test_df[cols].groupby('filename')

In [42]:
groupby_obj_train

In [44]:
groupby_obj_train.groups.keys()

dict_keys(['04ecd245-motorbike_0085.jpg', '10573c8e-dog_0090.jpg', '116e69df-airplane_0627.jpg', '17784d59-motorbike_0099.jpg', '1921e510-motorbike_0066.jpg', '29be3592-person_0187.jpg', '2bee9de4-dog_0084.jpg', '32474c4e-person_0179.jpg', '33045373-hr4.jpg', '34d9f740-car_0117.jpg', '3644dc32-dog_0092.jpg', '39500511-dog_0059.jpg', '3d7af1a8-person_0180.jpg', '3eb7022d-person_0176.jpg', '4151a21b-airplane_0589.jpg', '444ffcd6-motorbike_0065.jpg', '45aee029-3.jpeg', '475383e1-airplane_0629.jpg', '49706a9f-airplane_0628.jpg', '49840592-airplane_0585.jpg', '4a1ab8d7-person_0186.jpg', '4a245f79-car_0089.jpg', '4f3b3a54-br4.jpg', '531dad8b-person_0172.jpg', '53aeaf4e-motorbike_0051.jpg', '55bf0039-2.png', '564cfa86-4.jpg', '569d434a-car_0090.jpg', '581de111-dog_0079.jpg', '623f6da2-bus6.jpg', '6473826b-airplane_0582.jpg', '66ccbac9-2.jpg', '6b843422-car_0119.jpg', '7989cb0a-dog_0060.jpg', '79f7b169-dog_0076.jpg', '7a3719ef-5.jpg', '7ade3531-bus3.jpg', '7afda386-car_0109.jpg', '8124c265-car_0110.jpg', '8d7e24f8-3.jpg', '8ecadcd0-car_0091.jpg', '90559556-car_0116.jpg', '949db435-bus7.jpg', '973e0c90-car_0125.jpg', '998338b6-person_0175.jpg', '9d473d76-motorbike_0068.jpg', '9f984b70-car_0087.jpg', 'a21c2d4f-airplane_0584.jpg', 'a4003837-airplane_0587.jpg', 'a6591ab8-dog_0077.jpg', 'aceca466-person_0168.jpg', 'ae467a67-dog_0061.jpg', 'b0a12eaa-airplane_0588.jpg', 'b878f747-car_0093.jpg', 'b9555cf7-hr3.jpeg', 'b9bfa62a-dog_0091.jpg', 'baa5ec6c-br1.jpg', 'c23ee283-bus8.jpg', 'c891c28f-person_0171.jpg', 'd0d41c30-dog_0080.jpg', 'd5706038-dog_0049.jpg', 'dedd670d-car_0108.jpg', 'deefc9af-1.jpg', 'e0d36eea-car_0105.jpg', 'ef75bf34-br3.jpg', 'f3a143c5-motorbike_0052.jpg', 'f8d5864d-bus2.jpg', 'fc28c640-car_0088.jpg', 'fc8a8959-dog_0083.jpg', 'ffedcafd-br5.jpg'])

In [43]:
groupby_obj_test

In [45]:
groupby_obj_test.groups.keys()

dict_keys(['113003e8-car_0115.jpg', '2cac86c3-airplane_0586.jpg', '35ea7f19-dog_0067.jpg', '4a6a4480-dog_0081.jpg', '4ef7a026-airplane_0583.jpg', '561537ab-br2.jpg', '7d538689-hr2.jpg', '7e2729e3-car_0092.jpg', '9005d77c-dog_0045.jpg', '993b7094-person_0177.jpg', 'a3f61bb4-hr1.jpg', 'cb73af37-dog_0046.jpg', 'cb81b50c-bus1.jpg', 'd1a9bc81-bus4.jpg', 'f980c231-motorbike_0050.jpg', 'fbe49472-dog_0088.jpg', 'fcbb17d3-car_0113.jpg'])

In [34]:
# groupby_obj_train.get_group('04ecd245-motorbike_0085.jpg') ## convert to csvb

In [35]:
# groupby_obj_train.get_group('04ecd245-motorbike_0085.jpg').set_index('filename').to_csv('sample.txt',index=False,header=False)

In [36]:
# groupby_obj_train.get_group('10573c8e-dog_0090.jpg').set_index('filename').to_csv('sample.txt' , index=False,header=False)

# # ##it creates a sample txt with for the image 
# # ##main job is to write down all images with sample in trainfoldetr

In [37]:
# def save_data(filename , folder_path , group_obj):
#     ##moving images
#     src = os.path.join('data_images',filename)
#     dst = os.path.join(folder_path,filename)
#     move(src,dst)  #3moving images to destination folder
    
#     #saving the labels
    
# #     text_filename = os.path.splittext(filename)[0]+'.txt'
#     text_filename = os.path.join(folder_path , os.path.splitext(filename)[0]+'.txt')
#     group_obj.get_group(filename).set_index('filename').to_csv(text_filename ,sep=' ', index=False,header=False)

In [38]:
# ##apply in 
# groupby_obj_train.groups.keys()  ##dictionary

In [39]:
# https://app.cvat.ai/projects/70738?page=1
##corresponding .txt of the annoates images with train test val 1.11 resume

In [40]:
filename_series = pd.Series(groupby_obj_train.groups.keys())

In [41]:
filename_series.head()

0    04ecd245-motorbike_0085.jpg
1          10573c8e-dog_0090.jpg
2     116e69df-airplane_0627.jpg
3    17784d59-motorbike_0099.jpg
4    1921e510-motorbike_0066.jpg
dtype: object

In [38]:
##Ultralytics ## https://github.com/ultralytics  other ways 

# https://app.roboflow.com/suruj-kalita-chdxd

##roboflow ANFD ULTRALYTICS
#CVAT for dESCRIBING TXXT THE TRAIN AND TEST

In [39]:
# pip install ultralytics
# pip install roboflow

In [40]:
##Ultralytics ## https://github.com/ultralytics #MORE LABELLING IMAGES 
# https://github.com/MuhammadMoinFaisal/Computervisionprojects/tree/main/YOLOv8-CrashCourse

In [41]:
from ultralytics import YOLO
import numpy as np
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
import math

In [42]:
model = YOLO('yolov8n.pt')  ##downloading the weights

In [43]:
results = model('data_images/14.jpg' , show=True) ##predicting on the images
#./data_image
cv2.waitKey(0)  ##perfect prdictions #3already trained

image 1/1 C:\Users\SURUJ_KALITA\Desktop\pr-sd\myenv\data_images\14.jpg: 448x640 9 persons, 6 motorcycles, 120.0ms
Speed: 5.2ms preprocess, 120.0ms inference, 3.0ms postprocess per image at shape (1, 3, 448, 640)

-1

In [44]:
###############################3

In [48]:
# https://app.cvat.ai/tasks/create  
#https://www.youtube.com/watch?v=m9fH9OWn8YM&t=585s  upto train.txt 30min